### PR TITLE
English and Chinese typos (reopened)

### PR DESCRIPTION
**Pull request by mhs54321**
- Fixing several lowercase "l"s where there should actually be "1"s in the Chinese Tobit/Wisdom/Maccabees.
- Fixing the minor KJV typos.
- Also fixing a serious typo in Wisdom 5:14. Should be "ungodly", not "Godly"! Compare w' Septuagint and KJV: http://www.kingjamesbibleonline.org/1611-Bible-KJV/Wisdom-of-Solomon-Chapter-4-6.jpg

### CODE REVIEW

**Comment by typiconman** [comment]
I am out of town right now. I will review this asap. Thanks for the commit.

**Comment by typiconman** [comment]
Changes to English text LGTM. @stmitrophan please comment on the Chinese changes.

**Comment by typiconman** [comment]
@stmitrophan Can you take a look at this please and OK the push? It's been languishing for almost a year!

**Comment by mhs54321** [comment]
Actually, these changes encompass only ASCII characters. A Chinese reviewer
is not needed in this particular case.

The errors are missing pipe "|" symbols after certain verse numbers, and/or
the letter "l" where there should have been a number "1" in a verse number,
etc. (I'm guessing OCR artifacts or human typos). Other online copies of
these texts have the same errors. In Ponomar, these are causing these
specific Chinese chapters to fail to display.

**Comment by typiconman** [comment]
Merged. Thanks @mhs54321 for your contribution!

**Pull request merged**
